### ISSUE TITLE
Crash caused by modulo zero

### ISSUE THREAD

**Issue by rafzi** [memononen/recastnavigation#55]
In DetourNavMeshQuery.cpp function getPortalPoints line 2216:

	const int v1 = fromPoly->verts[(link->edge+1) % (int)fromPoly->vertCount];

my program crashed because the value of fromPoly->vertCount is zero:

```
Program terminated with signal 8, Arithmetic exception.
#0  0x00007f6a460f8c7b in dtNavMeshQuery::getPortalPoints (this=0x7f6a2b246de0, from=4414683, fromPoly=0x7886660,
    fromTile=0x7f6a2b1e2518, to=8608777, toPoly=0x7884c20, toTile=0x7f6a2b1e2518, left=0x7f6a49580460,
    right=0x7f6a49580450) at /home/recode/recode_systems/src/navigation/Detour/Source/DetourNavMeshQuery.cpp:2216
```

It is called by getEdgeMidPoint and this is called by findPath.

findPath is passing the parameter "bestPoly" as "fromPoly" to getEdgeMidPoint. bestPoly->vertCount is zero.

The issue seems to be that the navmesh generation build a mesh that contains polygons with size zero.

I just have the core dump, but if you need further information please ask.

**Comment by Paranaix** [comment]
Is this still occuring, any progress?

**Comment by leif81** [comment]
> The issue seems to be that the navmesh generation build a mesh that contains polygons with size zero.

Indeed, it sounds like the navmesh you're using is malformed. Fix that and this problem should away?

**Comment by Paranaix** [comment]
Malformed data shouldn't cvrash any proper software though

**Comment by memononen** [comment]
There's a system in place to detect common cases of "bad" data, such as
passing in wrong format. I really rigorous input check is needed, I will
accept contribution of dtValidateData() function :)

Navmesh polygons should have >= 3 vertices. With the exception of off-mesh,
which has 2 points (OMLs have also polygon representation to make the
search simple). The bake process guarantees this.

--mikko

**Comment by rafzi** [comment]
I don't have enough information to know how the bad data could have been created, but I understand that there is the >= 3 verts assumption.
