### ISSUE TITLE
Raycast Crash

### ISSUE THREAD

**Issue by bendangelo** [memononen/recastnavigation#92]
DetourNavMeshQuery.cpp:2429

```
hit->path[n++] = curRef;
```

Any idea why this is happening?

**Comment by memononen** [comment]
What are the inputs to the raycast when the crash happens? Most likely, you the `maxPaht` you pass is larger than what you have allocated in `path`.

**Comment by bendangelo** [comment]
I just created a dtRaycastHit without setting anything. I thought that was an option.

**Comment by memononen** [comment]
You need to also allocate data for the path buffer.

**Comment by bendangelo** [comment]
That fixes the problem, thanks.
